---
settings:
  name: ONTAP Cloud 9.3 release notes
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  versions:
  - name: ONTAP Cloud
    url: "/cloud-volumes-ontap-93-relnotes"
    version-number: '9.3'
  - name: Cloud Volumes ONTAP aktuell
    url: "/cloud-volumes-ontap-relnotes"
    version-number: ''
  - name: Andere Versionen
    url: https://docs.netapp.com/us-en/cloud-volumes-ontap-relnotes/reference-other-versions.html
    version-number: ''
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr
sidebar:
  entries:
  - title: Versionshinweise zu Hause
    url: "/index.html"
  - title: Was ist neu
    url: "/reference-new.html"
  - title: Unterstützte Konfigurationen
    url: "/reference-supported-configs.html"
  - title: Storage-Beschränkungen
    url: "/reference-storage-limits.html"
  - title: Bekannte Probleme
    url: "/reference-issues.html"
  - title: Bekannte Einschränkungen
    url: "/reference-limitations.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
homepage:
  tiles:
  - title: Los geht's
    links:
    - title: Was ist neu
      url: reference-new.html
  - title: Konfigurationen und Einschränkungen
    links:
    - title: Unterstützte Konfigurationen
      url: reference-supported-configs.html
    - title: Storage-Beschränkungen
      url: reference-storage-limits.html
    - title: Einschränkungen
      url: reference-limitations.html
  - title: Blogs Community
    links:
    - title: NetApp Community
      url: https://community.netapp.com/t5/Cloud-Data-Services/ct-p/CDS
    - title: Cloud Central Blog
      url: https://cloud.netapp.com/blog
    - title: Cloud-Webinare
      url: https://cloud.netapp.com/events
product-family:
  name: BlueXP
  repo: cloud-manager-family
  sidebar_label: Alle Dokumentationen zum Cloud Manager
