---
sidebar: sidebar 
permalink: reference-supported-configs.html 
keywords: ec2, instance, type, vm, explore, standard, premium, byol, capacity, maximum, virtual machine, ontap cloud, supported, configurations 
summary: ONTAP Cloud ist in verschiedenen Konfigurationen in AWS und Azure erhältlich. 
---
= Unterstützte Konfigurationen
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
ONTAP Cloud ist in AWS und Azure in zwei Preisoptionen erhältlich: Nutzungsbasiert und als BYOL-Modell (Bring-Your-Own-License). Für „Pay-as-you-go“ haben Sie die Wahl zwischen drei Konfigurationen: Explore, Standard oder Premium.



== ONTAP Cloud für AWS

In AWS können Sie ONTAP Cloud als einzelnes System oder als HA-Paar implementieren.

[cols="h,d,d,d,d"]
|===
|  | Entdecken | Standard | Premium | BYOL 


| EC2 Instanztypen | m4.xlarge  a| 
* M4.2xlarge
* r4.xlarge

 a| 
* C4.4xlarge
* C4.8xlarge
* M4.4xlarge
* R4.2xlarge

 a| 
* C4.4xlarge
* C4.8xlarge
* m4.xlarge
* M4.2xlarge
* M4.4xlarge
* r4.xlarge
* R4.2xlarge




| Zugrunde liegender Storage 4+| Universell einsetzbare SSDs, bereitgestellte IOPS-SSDs, durchsatzoptimierte HDDs und kalte HDDs, bis zu 16 tib pro Festplatte 


| Limit für Lizenzkapazität | 2 tib | 10 tib | 368 tib | 368 tib pro Lizenz 
|===
Hinweise:

. Pay-as-you-go-Konfigurationen werden in GovCloud (US) nicht unterstützt.
. Wenn Sie einen EC2-Instanztyp auswählen, können Sie angeben, ob es sich um eine freigegebene Instanz oder eine dedizierte Instanz handelt.
. Eine verbesserte Schreib-Performance wird unterstützt, wenn EBS-SSDs mit ONTAP Cloud-Standard, Premium und BYOL verwendet werden.
. Daten-Tiering wird mit ONTAP Cloud Standard, Premium und BYOL unterstützt.
. Wenn Sie Data Tiering aktivieren, bleibt die Kapazitätsgrenze eines Systems gleich. Die Kapazitätsgrenze gilt sowohl für Festplatten als auch für Objekt-Storage.
. Informationen zu regionalen Support für AWS finden Sie unter https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes Regionen Weltweit"].




== ONTAP Cloud für Azure

In Azure können Sie ONTAP Cloud als Single-Node-System implementieren.

[cols="h,d,d,d,d"]
|===
|  | Entdecken | Standard | Premium | BYOL 


| Typen von Virtual Machines | DS3_v2  a| 
* DS4_v2
* DS13_v2

 a| 
* DS5_v2
* DS14_v2

 a| 
* DS3_v2
* DS4_v2
* DS5_v2
* DS13_v2
* DS14_v2




| Zugrunde liegender Storage 4+| Standard-HDD-verwaltete Festplatten, Standard-SSD-verwaltete Festplatten und Premium-SSD-gemanagte Festplatten für bis zu 32 tib pro Festplatte 


| Limit für Lizenzkapazität | 2 tib | 10 tib | 368 tib | 368 tib pro Lizenz 
|===
Hinweise:

. Eine verbesserte Schreib-Performance wird unterstützt, wenn Azure Premium Storage-Festplatten mit ONTAP Cloud Standard, Premium und BYOL verwendet werden, jedoch nicht bei Verwendung des Virtual Machine-Typs DS3_v2.
. Informationen zur regionalen Unterstützung für Azure finden Sie unter https://cloud.netapp.com/cloud-volumes-global-regions["Cloud Volumes Regionen Weltweit"].

